# render.yaml
services:
  - type: web
    name: medical-records-api
    env: dotnet
    region: oregon
    plan: free
    disk:
      name: app-data
      mountPath: /app/uploads
      sizeGB: 10
    buildCommand: |
      cd backend/src
      dotnet restore
      dotnet publish MedicalRecords.API/MedicalRecords.API.csproj -c Release -o ../publish --no-restore
    startCommand: cd backend/publish && dotnet MedicalRecords.API.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: ASPNETCORE_FORWARDEDHEADERS_ENABLED
        value: true
      - key: FileStorage__BasePath
        value: /app/uploads
      - key: FileStorage__MaxFileSize
        value: 52428800
      - key: DATABASE_URL
        fromDatabase:
          name: medical-records-db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: medical-records-db
    databaseName: medicalrecords
    user: medicaluser
    plan: free
